const KEY="fightTrackingV2";
const defaults={profile:{name:"Lubna",initial:"LB",belt:"Green Belt"},theme:{accent:"red",mode:"dark"},goals:{sessions:5,kicks:1000},
trainings:[{date:"09 Sep 2026",type:"Sparring",duration:"90 min",intensity:"High",xp:120,icon:"⚔"},{date:"07 Sep 2026",type:"Kicking",duration:"60 min",intensity:"Medium",xp:90,icon:"🦵"},{date:"05 Sep 2026",type:"Strength",duration:"75 min",intensity:"High",xp:100,icon:"💪"},{date:"03 Sep 2026",type:"Poomsae",duration:"60 min",intensity:"Medium",xp:80,icon:"🥋"}],
matches:[{event:"Kejuaraan Kota 2026",date:"30 Aug 2026",opponent:"Raka P.",score:"8 - 5",result:"WIN"},{event:"Friendly Sparring",date:"21 Aug 2026",opponent:"Dimas R.",score:"4 - 6",result:"LOSS"}],
kicks:[{name:"Dollyo Chagi",mastery:82,reps:420,change:"+8%"},{name:"Ap Chagi",mastery:76,reps:530,change:"+12%"},{name:"Yop Chagi",mastery:63,reps:280,change:"+5%"},{name:"Dwi Chagi",mastery:55,reps:190,change:"+15%"}],
achievements:[{icon:"🔥",name:"7 Day Streak",desc:"7 hari latihan berturut-turut",xp:100,earned:true},{icon:"🦵",name:"Kick Master",desc:"1,000 repetisi tendangan",xp:250,earned:true},{icon:"⚔️",name:"First Victory",desc:"Menang pertandingan pertama",xp:150,earned:true},{icon:"💪",name:"No Excuses",desc:"30 sesi latihan",xp:300,earned:false},{icon:"🏆",name:"Tournament Ready",desc:"Ikuti 10 pertandingan",xp:400,earned:false},{icon:"🥋",name:"Belt Up",desc:"Naik satu tingkat sabuk",xp:500,earned:false}]};
let db=JSON.parse(localStorage.getItem(KEY)||"null")||structuredClone(defaults);
const $=s=>document.querySelector(s), esc=s=>String(s).replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[c]));
function save(){localStorage.setItem(KEY,JSON.stringify(db));applyTheme();render();toast("Tersimpan ✓")}
function toast(t){const x=$("#toast");x.textContent=t;x.classList.add("show");setTimeout(()=>x.classList.remove("show"),1600)}
const pages=["dashboard","training","matches","kicks","ranking","achievements","settings"];
function go(p){pages.forEach(x=>$("#"+x).classList.toggle("active",x===p));document.querySelectorAll(".nav").forEach(x=>x.classList.toggle("active",x.dataset.page===p));$("#pageTitle").textContent={dashboard:"Dashboard",training:"Latihan",matches:"Pertandingan",kicks:"Tendangan",ranking:"Ranking",achievements:"Achievement",settings:"Customize"}[p];render()}
document.querySelectorAll(".nav").forEach(b=>b.onclick=()=>go(b.dataset.page));document.querySelectorAll("[data-go]").forEach(b=>b.onclick=()=>go(b.dataset.go));
$("#quickAdd").onclick=()=>addTraining();

function xp(){return db.trainings.reduce((a,x)=>a+Number(x.xp||0),0)+db.achievements.filter(x=>x.earned).reduce((a,x)=>a+Number(x.xp||0),0)}
function render(){
 $("#topXP").textContent=xp().toLocaleString("id-ID");$("#miniName").textContent=db.profile.name;$("#miniBelt").textContent=db.profile.belt;$("#avatar").textContent=db.profile.initial||"FT";
 const beltNext={ "White Belt":["Yellow Belt",15],"Yellow Belt":["Green Belt",32],"Green Belt":["Blue Belt",68],"Blue Belt":["Red Belt",82],"Red Belt":["Black Belt",94],"Black Belt":["MASTER",100]}[db.profile.belt]||["NEXT",50];$("#beltPct").textContent=beltNext[1]+"%";$("#nextBelt").textContent="TO "+beltNext[0].toUpperCase();
 const wins=db.matches.filter(x=>x.result==="WIN").length,loss=db.matches.filter(x=>x.result==="LOSS").length,total=wins+loss,wr=total?((wins/total)*100).toFixed(1):"0.0";
 $("#stats").innerHTML=[["WIN RATE",wr+"%","↗ "+wins+"W / "+loss+"L",""],["STREAK",Math.min(14,db.trainings.length+3)+" days","🔥 Keep going","Best: 14 days"],["RANKING","#08","↑ 3 places","Top 10 club"],["SESSIONS",db.trainings.length,"+"+db.trainings.length+" logged","Goal: "+db.goals.sessions+"/week"]].map(x=>`<div class="stat"><small>${x[0]}</small><b>${x[1]}</b><span>${x[2]}</span><i>${x[3]}</i></div>`).join("");
 $("#bars").innerHTML=[55,82,45,96,70,40,65].map((v,i)=>`<div><i style="height:${v}%"></i><small>${["M","T","W","T","F","S","S"][i]}</small></div>`).join("");
 $("#dashSchedule").innerHTML=defaultSchedules().map(x=>`<div class="schedule"><div class="date"><b>${x[0]}</b><small>${x[1]}</small></div><div><b>${x[2]}</b><small>${x[3]} • ${x[4]}</small></div></div>`).join("");
 $("#dashKicks").innerHTML=db.kicks.slice(0,3).map(k=>`<div class="kick"><div class="kicktitle"><b>${esc(k.name)}</b><strong>${k.mastery}%</strong></div><div class="kickbar"><i style="width:${k.mastery}%"></i></div></div>`).join("");
 $("#dashAch").innerHTML=db.achievements.filter(a=>a.earned).slice(0,3).map(a=>`<div class="achrow"><span>${a.icon}</span><div><b>${esc(a.name)}</b><small>${esc(a.desc)}</small></div><strong>+${a.xp} XP</strong></div>`).join("");
 $("#trainingSummary").innerHTML=[["SESSIONS",db.trainings.length,"logged"],["XP",db.trainings.reduce((a,x)=>a+x.xp,0),"this tracker"],["TARGET",db.goals.sessions,"sessions / week"]].map(x=>`<div class="card"><small>${x[0]}</small><b>${x[1]}</b><p class="hint">${x[2]}</p></div>`).join("");
 $("#trainingRows").innerHTML=db.trainings.map((x,i)=>`<div class="trainingrow"><div class="type">${x.icon||"🥋"}</div><div><b>${esc(x.type)}</b><small>${esc(x.date)} • ${esc(x.duration)} • ${esc(x.intensity)}</small></div><span class="xp">+${x.xp} XP</span><button class="ghost" onclick="delTraining(${i})">×</button></div>`).join("")||`<p class="hint">Belum ada latihan. Tambahkan latihan pertama kamu.</p>`;
 $("#matchStats").innerHTML=[["MATCHES",total],["WINS",wins],["LOSSES",loss],["WIN RATE",wr+"%"]].map(x=>`<div class="stat"><small>${x[0]}</small><b>${x[1]}</b></div>`).join("");
 $("#matchRows").innerHTML=db.matches.map((x,i)=>`<div class="matchrow"><div><b>${esc(x.event)}</b><small>${esc(x.date)} • vs ${esc(x.opponent)}</small></div><strong>${esc(x.score)}</strong><span class="result ${x.result==="WIN"?"win":"loss"}">${x.result}</span><button class="ghost" onclick="delMatch(${i})">×</button></div>`).join("")||`<p class="hint">Belum ada pertandingan.</p>`;
 $("#kickGrid").innerHTML=db.kicks.map((k,i)=>`<article class="kickcard"><div class="kicktitle"><b>${esc(k.name)}</b><strong>${k.mastery}%</strong></div><div class="kickbar"><i style="width:${k.mastery}%"></i></div><div class="kickmeta"><span>${k.reps} reps</span><span>${esc(k.change)}</span><button class="ghost" onclick="editKick(${i})">Edit</button><button class="ghost" onclick="delKick(${i})">×</button></div></article>`).join("");
 const ranks=[["01","Andra","2,450 XP","Black Belt"],["02","Naya","2,210 XP","Red Belt"],["03","Dimas","1,980 XP","Blue Belt"],["08",db.profile.name,xp().toLocaleString("id-ID")+" XP",db.profile.belt]];
 $("#rankRows").innerHTML=ranks.map((r,i)=>`<div class="rankrow ${i===3?"rankyou":""}"><span>${r[0]}</span><div class="rankavatar">${i===3?esc(db.profile.initial):r[1][0]}</div><div><b>${esc(r[1])}</b><small>${esc(r[3])}</small></div><strong>${r[2]}</strong></div>`).join("");
 $("#achGrid").innerHTML=db.achievements.map((a,i)=>`<article class="achievement ${a.earned?"earned":"locked"}"><div class="icon">${a.icon}</div><h3>${esc(a.name)}</h3><p>${esc(a.desc)}</p><small>${a.earned?"✓ Unlocked":"＋"+a.xp+" XP"}</small><br><button class="ghost" onclick="toggleAch(${i})">${a.earned?"Lock":"Unlock"}</button><button class="ghost" onclick="delAch(${i})">×</button></article>`).join("");
 $("#setName").value=db.profile.name;$("#setInitial").value=db.profile.initial;$("#setBelt").value=db.profile.belt;$("#setAccent").value=db.theme.accent;$("#setMode").value=db.theme.mode;$("#setGoal").value=db.goals.sessions;$("#setKickGoal").value=db.goals.kicks||1000;
}
function defaultSchedules(){return [["10","SEP","Technique & Kicking","16:00","90 min"],["12","SEP","Sparring","16:30","90 min"],["14","SEP","Strength & Conditioning","08:00","75 min"]]}
function addTraining(){let type=prompt("Jenis latihan?","Kicking");if(!type)return;let dur=prompt("Durasi?","60 min");if(!dur)return;let intensity=prompt("Intensitas? Low / Medium / High","Medium")||"Medium";db.trainings.unshift({date:new Date().toLocaleDateString("id-ID",{day:"2-digit",month:"short",year:"numeric"}),type,duration:dur,intensity,xp:80,icon:type.toLowerCase().includes("kick")?"🦵":"🥋"});save();go("training")}
function delTraining(i){if(confirm("Hapus sesi ini?")){db.trainings.splice(i,1);save()}} function clearTrainings(){if(confirm("Reset semua latihan?")){db.trainings=[];save()}}
function addMatch(){let event=prompt("Nama pertandingan?","Friendly Match");if(!event)return;let opponent=prompt("Nama lawan?","Opponent")||"Opponent";let result=(prompt("WIN atau LOSS?","WIN")||"WIN").toUpperCase();if(!["WIN","LOSS"].includes(result))result="WIN";let score=prompt("Skor?","-")||"-";db.matches.unshift({event,date:new Date().toLocaleDateString("id-ID",{day:"2-digit",month:"short",year:"numeric"}),opponent,score,result});save();go("matches")}
function delMatch(i){if(confirm("Hapus match ini?")){db.matches.splice(i,1);save()}}
function addKick(){let name=prompt("Nama teknik tendangan?","Neryo Chagi");if(!name)return;let mastery=+prompt("Mastery 0-100?","50")||50;let reps=+prompt("Jumlah repetisi?","100")||100;db.kicks.push({name,mastery:Math.max(0,Math.min(100,mastery)),reps,change:"+0%"});save();go("kicks")}
function editKick(i){let m=+prompt("Mastery baru (0-100)",db.kicks[i].mastery);if(Number.isNaN(m))return;db.kicks[i].mastery=Math.max(0,Math.min(100,m));let r=+prompt("Repetisi",db.kicks[i].reps);if(!Number.isNaN(r))db.kicks[i].reps=r;save()}
function delKick(i){if(confirm("Hapus teknik ini?")){db.kicks.splice(i,1);save()}}
function addAchievement(){let name=prompt("Nama achievement?","New Achievement");if(!name)return;let desc=prompt("Deskripsi?","Achievement custom");let xp=+prompt("XP reward?","100")||100;db.achievements.push({icon:"🏅",name,desc,xp,earned:false});save();go("achievements")}
function toggleAch(i){db.achievements[i].earned=!db.achievements[i].earned;save()}function delAch(i){if(confirm("Hapus achievement?")){db.achievements.splice(i,1);save()}}
function saveProfile(){db.profile.name=$("#setName").value||"Athlete";db.profile.initial=($("#setInitial").value||"FT").slice(0,3).toUpperCase();db.profile.belt=$("#setBelt").value;save()}
function saveTheme(){db.theme.accent=$("#setAccent").value;db.theme.mode=$("#setMode").value;save()}
function saveGoals(){db.goals.sessions=Math.max(1,+$("#setGoal").value||5);db.goals.kicks=Math.max(100,+$("#setKickGoal").value||1000);save()}
function applyTheme(){document.documentElement.style.setProperty("--accent",{red:"#ef3b36",lime:"#a6e637",blue:"#3c8dff",purple:"#a56bff"}[db.theme.accent]||"#ef3b36");document.body.classList.toggle("light",db.theme.mode==="light");document.body.classList.toggle("midnight",db.theme.mode==="midnight")}
function resetAll(){if(confirm("Hapus semua data dan kembali ke default?")){localStorage.removeItem(KEY);db=structuredClone(defaults);applyTheme();render();toast("Data direset")}}
const player=$("#player"),songInput=$("#songInput"),musicBtn=$("#musicBtn");
musicBtn.onclick=async()=>{if(!player.src)player.src="assets/song.mp3";if(player.paused){try{await player.play()}catch(e){songInput.click();return}}else player.pause();updateMusic()};
songInput.onchange=e=>{let f=e.target.files[0];if(f){player.src=URL.createObjectURL(f);player.play();updateMusic()}};
function updateMusic(){musicBtn.querySelector("em").textContent=player.paused?"OFF":"ON";musicBtn.firstChild.textContent=player.paused?"♫ ":"Ⅱ "}
applyTheme();render();
